package top.lizhanqi.www.zxing.scanner;

/**
 * ......................我佛慈悲....................
 * ......................_oo0oo_.....................
 * .....................o8888888o....................
 * .....................88" . "88....................
 * .....................(| -_- |)....................
 * .....................0\  =  /0....................
 * ...................___/`---'\___..................
 * ..................' \\|     |// '.................
 * ................./ \\|||  :  |||// \..............
 * .............../ _||||| -卍-|||||- \..............
 * ..............|   | \\\  -  /// |   |.............
 * ..............| \_|  ''\---/''  |_/ |.............
 * ..............\  .-\__  '-'  ___/-. /.............
 * ............___'. .'  /--.--\  `. .'___...........
 * .........."" '<  `.___\_<|>_/___.' >' ""..........
 * ........| | :  `- \`.;`\ _ /`;.`/ - ` : | |.......
 * ........\  \ `_.   \_ __\ /__ _/   .-` /  /.......
 * ....=====`-.____`.___ \_____/___.-`___.-'=====....
 * ......................`=---='.....................
 * ..................佛祖开光 ,永无BUG................
 *
 * @author Created by 李站旗 on 2018/6/30 0030 13:21 .
 * QQ:1032992210
 * E-mail:lizhanqihd@163.com
 * @Description: todo(用一句话描述该文件做什么)
 */
public class StaticCode {


    public static final int decode=1880;
    public static final int  capture_scan_photo=1881;
    public static final int  auto_focus=1882;
    public static final int  decode_failed=1883;
    public static final int  quit=1884;
    public static final int  decode_succeeded=1885;
    public static final int  encode_failed=1886;
    public static final int  return_scan_result=1887;
    public static final int  restart_preview=1888;
  public static final int  capture_flashlight=1889;
    public static final int  launch_product_query=1890;

}
